in_class_site/urls.py
from django.conf.urls import url
from django.contrib import admin

from app.views import make_index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', make_index)
]

app/models.py
from django.db import models

# Create your models here.

PLAYER_POSITIONS = [
    ('RD', 'Right Defense'),
    ('LD', 'Left Defense'),
    ('C', 'Center'),
    ('RW', 'Right Wing'),
    ('LW', 'Left Wing'),
    ('G', 'Goaltender')
]

class Stat(models.Model):
    name = models.CharField(max_length=30)
    number = models.IntegerField(default=0)
    player_position = models.CharField(max_length=20, choices=PLAYER_POSITIONS, default='G')
    weight = models.IntegerField(default=0)
    image_url = models.CharField(max_length=200)

    def __str__(self):
        return "{} {} {} {}".format(self.name, self.number, self.player_position,
                                    self.weight)

app/views.py
from django.http import HttpResponse
from django.shortcuts import render, render_to_response


# Create your views here.
from app.models import Stat


def make_index(request):
    all_players = Stat.objects.all()
    return render_to_response("index.html", {"players": all_players})

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sports Stats</title>
    <style>
        table, th, td {
            border: 0px solid black;
        }
        th, td {
            padding: 1px;
            text-align: left
        }
    </style>
</head>
<body>
<h1>Boston Bruins 2010-2011 Players</h1>

<table style="width:100%">
    {% for player in players %}
        <tr>
            <th>{{ player.name }}</th>
            <th>Stats</th>
        </tr>

        <tr>
            <td rowspan="4" width="200"><img src={{ player.image_url }} style="height:128px;"></td>
        </tr>

            <tr>
                <td>Number: {{ player.number }}</td>
            </tr>
            <tr>
                <td>Position: {{ player.get_player_position_display }}</td>
            </tr>
            <tr>
                <td>Weight: {{ player.weight }}</td>
            </tr>
        <tr><th><p></p></th></tr>
        <tr><th><p></p></th></tr>



{% endfor %}

</table>
</body>
</html>